# Generated by Django 4.2.6 on 2023-11-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_comment_name_alter_comment_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="name",
            field=models.CharField(db_index=True, max_length=64, null=True),
        ),
    ]
