# Generated by Django 4.2.6 on 2023-11-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_comment_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_image", models.ImageField(upload_to="images/")),
                ("thumbnail", models.ImageField(upload_to="images/thumbnails/")),
            ],
        ),
    ]
