# Generated by Django 4.0.6 on 2023-10-12 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('content', models.TextField()),
            ],
            options={
                'permissions': [('can_alter_content', 'Can alter documents content')],
            },
        ),
    ]
