# Generated by Django 4.0.6 on 2023-10-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_document_options_document_is_open_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=128)),
                ('is_open', models.BooleanField()),
            ],
            options={
                'permissions': [('can_open', 'Can open & close book'), ('can_write_summary', 'Can add summary to book'), ('can_change_metadata', 'Can change books metadata')],
            },
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
