# Generated by Django 4.2.6 on 2023-10-18 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("name", models.CharField(max_length=64)),
                ("author", models.CharField(max_length=128)),
            ],
        ),
    ]
